version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: smart_sales_postgres
    environment:
      POSTGRES_DB: smart_sales
      POSTGRES_USER: smart_sales_user
      POSTGRES_PASSWORD: smart_sales_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smart_sales_user -d smart_sales"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
